import {
  Activity,
  BarChart3,
  Bot,
  Calendar,
  Check,
  Cloud,
  Cpu,
  Droplet,
  Dumbbell,
  ExternalLink,
  Flame,
  GitBranch,
  Home,
  LayoutGrid,
  List,
  LogOut,
  Menu,
  Moon,
  Plus,
  Server,
  Settings,
  StickyNote,
  Sun,
  Target,
  Trash2,
  X,
  type LucideIcon,
} from "lucide-react";

// Project icon set, backed by lucide-react. The `IconName` union + `icons`
// record are kept so existing dynamic lookups (`icons[name]`) and call sites
// (`<icons.list />`) keep working unchanged.
export const icons = {
  check: Check,
  plus: Plus,
  list: List,
  grid: LayoutGrid,
  chart: BarChart3,
  menu: Menu,
  logout: LogOut,
  cpu: Cpu,
  pulse: Activity,
  note: StickyNote,
  bot: Bot,
  moon: Moon,
  sun: Sun,
  dumbbell: Dumbbell,
  drop: Droplet,
  target: Target,
  flame: Flame,
  server: Server,
  cloud: Cloud,
  home: Home,
  calendar: Calendar,
  close: X,
  trash: Trash2,
  git: GitBranch,
  external: ExternalLink,
  gear: Settings,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;
